version: "3.9"
services:
  trex:
    image: mfierbau/cisco-trex:3.06
    build:
      context: ./
      dockerfile: trex.Dockerfile
    container_name: "trex"
    hostname: "trex"
    stdin_open: true
    tty: true
    ports:
      - "4500:4500"
      - "4501:4501"
      - "4507:4507"
      - "4500:4500/udp"
      - "4501:4501/udp"
      - "4507:4507/udp"
    networks:
      management:
        ipv4_address: 172.90.0.2
        priority: 1000
      trex-1:
        ipv4_address: 172.100.0.2
        priority: 900
      trex-2:
        ipv4_address: 172.200.0.2
        priority: 800
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ["./t-rex-64", "-i", "--cfg", "/etc/trex_cfg.yaml"]
    privileged: true

networks:
  management:
    ipam:
      driver: default
      config:
        - subnet: 172.90.0.0/24
  trex-1:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24
  trex-2:
      ipam:
        driver: default
        config:
          - subnet: 172.200.0.0/24
